services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      elasticsearch-node1:
        condition: service_healthy  # Ensure Elasticsearch starts before the Flask app
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch-node1:9200  # Elasticsearch host URL
      - FLASK_DEBUG=true  # Enable Flask debug mode (for development)
      - RESET_INDEX=true  # Reset Elasticsearch index at startup (for testing)

  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: es-node1
    environment:
      - node.name=es-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node2,es-node3 # Lists the other nodes so they can discover each other
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3 # Specifies the initial set of master-eligible nodes for bootstrapping the cluster
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    # Only elasticsearch-node1 exposes 9200 to the host for external connections, the other nodes communicate internally
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data1:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: es-node2
    environment:
      - node.name=es-node2
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data2:/usr/share/elasticsearch/data

  elasticsearch-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: es-node3
    environment:
      - node.name=es-node3
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data3:/usr/share/elasticsearch/data

volumes:
  es_data1:
  es_data2:
  es_data3:
